### ISSUE TITLE
Adapter located in wrong category (type) in stable repository?

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.repositories#1447]
I've seen that the [PushBullet](https://github.com/Jens1809/ioBroker.pushbullet) adapter is located in "communications" in the ioBroker adapters default/stable list. The question is: why? The [io-package.json](https://github.com/Jens1809/ioBroker.pushbullet/blob/master/io-package.json) in the project is correct (type: "messaging") and even the repository files in this repo are correct (type: "messaging"):

https://github.com/ioBroker/ioBroker.repositories/blob/06f65ac470477e0c754b006f273a7ba8fce4b56d/sources-dist.json#L1390-L1394

https://github.com/ioBroker/ioBroker.repositories/blob/06f65ac470477e0c754b006f273a7ba8fce4b56d/sources-dist-stable.json#L1393-L1398

**Latest repository** [http://download.iobroker.net/sources-dist-latest.json](http://download.iobroker.net/sources-dist-latest.json) is also correct:

```
"pushbullet": {
    "meta": "https://raw.githubusercontent.com/Jens1809/ioBroker.pushbullet/master/io-package.json",
    "icon": "pushbullet.png",
    "type": "messaging",
    "stars": -1,
    "weekDownloads": 5,
    "stat": 372,
    "name": "pushbullet",
    "version": "0.0.11",
    "authors": [
      "Jens1809 &lt;cpthans@gmail.com&gt;"
    ],
    "title": "Pushbullet Adapter",
    "desc": "Pushbullet adapter",
    "platform": "Javascript/Node.js",
    "mode": "daemon",
    "messagebox": true,
    "extIcon": "https://raw.githubusercontent.com/Jens1809/ioBroker.pushbullet/master/admin/pushbullet.png",
    "loglevel": "info",
    "published": "2015-07-25T20:26:50.201Z",
    "versionDate": "2015-10-11T17:49:44.529Z",
    "stable": "0.0.11"
  },
```

## Issue

How is it possible, that the **stable repository file on download.iobroker.net delivers the wrong type communication**?

[http://repo.iobroker.live/sources-dist.json](http://repo.iobroker.live/sources-dist.json):
```
  "pushbullet": {
    "name": "pushbullet",
    "version": "0.0.11",
    "title": "Pushbullet Adapter",
    "desc": "Pushbullet adapter",
    "platform": "Javascript/Node.js",
    "mode": "daemon",
    "messagebox": true,
    "icon": "https://raw.githubusercontent.com/Jens1809/ioBroker.pushbullet/master/admin/pushbullet.png",
    "extIcon": "https://raw.githubusercontent.com/Jens1809/ioBroker.pushbullet/master/admin/pushbullet.png",
    "loglevel": "info",
    "type": "communication",
    "meta": "https://raw.githubusercontent.com/Jens1809/ioBroker.pushbullet/master/io-package.json",
    "published": "2015-07-25T20:26:50.201Z",
    "versionDate": "2015-10-11T17:49:44.529Z",
    "stars": -1,
    "stat": 372,
    "weekDownloads": 5,
    "latestVersion": "0.0.11",
    "issues": 9,
    "score": 1
  },
```

**Comment by mcm1957** [comment]
This is caused by outdated data within the release. The cahnged to io-package.json never made it into a release. 
see https://github.com/Jens1809/ioBroker.pushbullet/issues/42

sources-dist.json (stable) refers to last release version which still contained the other type.

no problem her - so lts close.
