### ISSUE TITLE
Nicht funktionierende Adapter wurde nach Stable verschoben

### ISSUE THREAD

**Issue by Knallochse** [ioBroker/ioBroker.repositories#1526]
Ich wollte informieren, das ein schon seit Jahren nicht mehr funktionierender Adapter nach Stable verschoben wurde.

> @@ -435,7 +435,7 @@
     "meta": "https://raw.githubusercontent.com/soef/ioBroker.find-my-iphone/master/io-package.json",
     "icon": "https://raw.githubusercontent.com/soef/ioBroker.find-my-iphone/master/admin/find-my-iphone.png",
     "type": "geoposition",
     "version": "0.2.15"
     "version": "0.2.17"

soef hat das letzte mal 2018 diesen Adapter gepflegt.

Außerdem ist dieser Teil der [Community Adapter ](https://github.com/iobroker-community-adapters/ioBroker.find-my-iphone-community). Aber auch in dieser Repo funktioniert er nicht. (Issues vorhanden)

Ebenfalls wurde diese Adapterversion

> "spotify-premium": {
     "meta": "https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.spotify-premium/master/io-package.json",
     "icon": "https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.spotify-premium/master/admin/spotify-premium.png",
     "type": "multimedia",
     "version": "1.0.0"
     "version": "1.1.3" 

nach Stable verschoben. Diese Version funktioniert nicht (Issues vorhanden)
Version 1.1.1 funktioniert eingeschränkt.

**Comment by Knallochse** [comment]
Da der Issues unkommentiet geschlossen wurde, aber der Find-my-Iphone Adapter (Repo soef)  weiterhin als Stable  gelistet ist, frage ich mich ob solche Hinweise meinerseits unerwünscht sind?

**Comment by Apollon77** [comment]
Nein, ich habe mich verkuckt .. werde es entfernen ...
