### ISSUE TITLE
Check for archived repositories and remove them from the adapter list

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.repositories#1782]
e.g. https://github.com/Kartax/ioBroker.binance

https://github.com/ioBroker/ioBroker.repositories/blob/1fb816c41a67098b2ed3256bca7c1ee1706acfe6/sources-dist-stable.json#L146-L151

**Comment by klein0r** [comment]
Please don't close this

**Comment by mcm1957** [comment]
PR #2321
new script lib/checkArchived.js
The script scans stable and latest repository and creates issues at ioBroker.repositories if:
-) an adapter is listed at stable but not at latest
-) an adapter repository is archived
-) an adapter repository is not accessible

The script does NOT manipulate repository files (*.json) in any way. Removed of adapters must be done manually. As this is a ruther seldom task, automatisation is too risky, espscially as an archived repository could also indiocate that an adpater should not be removed but moved to community area.

The script will be running once a week
