### ISSUE TITLE
LGTM.com will be shut down in December 2022

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.repositories#1959]
Ist zwar - glaub ich - schon bekannt. Ich erlaube mir aber hier ein Issue dazu zu öffnen damit es nicht untergeht und im Dezember dann Releases klemmen (da ja hier LTGM Tests laufen)

Zitat von der LTGM Webseite:
_LGTM.com will be shut down in December 2022 — we recommend that you use GitHub code scanning instead. Read more in [our blog post on the GitHub blog](https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/)._

**Comment by Apollon77** [comment]
Ok, btu why in this repo? it is not used here ... ?!

**Comment by mcm1957** [comment]
OK and sorry.
I was completly sure that I have seen th LTGM Test during creation of my last stable PR.
But you are right - I must have mixed up some repo views. I cannot find a LTGM Test currently.

**Comment by mcm1957** [comment]
OK, I got it. When creating a PR a LTGM Tests shows up:

![image](https://user-images.githubusercontent.com/28575778/194694975-533abee4-d032-46d4-a2bb-0541327994b8.png)

Ok, this test is located samewhere else... I'll discusse at telegram
