### ISSUE TITLE
[Feature] Check that adapter added to stable is included into latest repository

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.repositories#2058]
It looks like adding an adapter directly into the stable repository passes the automatic checks even if this adapter is not include into the latest repository.

I would suggest that a check should fail if a PR requests an adapter to be added into stable repository while this adapter is not added into the latest previously.

Ref: https://github.com/ioBroker/ioBroker.repositories/pull/2056

**Comment by raintonr** [comment]
Ermmmmm https://github.com/ioBroker/ioBroker.repositories/pull/2056#issuecomment-1349607371https://github.com/ioBroker/ioBroker.repositories/pull/2056#issuecomment-1349607371

**Comment by Apollon77** [comment]
There are checks
