### ISSUE TITLE
Pr erzeugt Fehler im Test.

### ISSUE THREAD

**Issue by BenAhrdt** [ioBroker/ioBroker.repositories#2242]
Bei mehreren prs wurde bei einem pr der Test angelernt wegen einem Fehler.
Bspw.
[https://github.com/BenAhrdt/ioBroker.repositories/actions/runs/4771647121](https://github.com/BenAhrdt/ioBroker.repositories/actions/runs/4771647121)

**Comment by mcm1957** [comment]
Wo siehst du da nen Fehler?

Der referenzierte Test wurde GECANCELT. Das ist m.E. durchaus normal da die Tests sobsufgesetzt sind dass zur Einsparung v Rechenzeit redundante Test vermiden werden.

Das hst zu dem Thema scon Apollon77 geantwortet
https://t.me/c/1697676361/3872

**Comment by BenAhrdt** [comment]
@mcm1957 
@Apollon77 hat mich gebeten das Issue hier auf zu machen.

**Comment by mcm1957** [comment]
OK, Thanks for the info
