### ISSUE TITLE
Drop adapter blink4home

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.repositories#2286]
https://github.com/Flashy-GER/ioBroker.blink4home/tree/master

- No update since 3 years
- A lot of complaints in the reviews
- Never left beta state

<img width="615" alt="Screenshot 2023-05-16 at 09 25 59" src="https://github.com/ioBroker/ioBroker.repositories/assets/1959049/089a6d2d-f53b-4c57-a7c5-ae945bef7875">

https://github.com/ioBroker/ioBroker.repositories/blob/420e8f9a24c8cd4d7e4911a3241982f98ed6bdb2/sources-dist.json#L177-L181

**Comment by Apollon77** [comment]
agreed. @mcm1957 Could you please do that?
Should we also inform the dev via an issue in his repo?

**Comment by Apollon77** [comment]
oookkk ... repo now got transferred to community so we coouulld try to fix it also ;-)

**Comment by mcm1957** [comment]
> oookkk ... repo now got transferred to community so we coouulld try to fix it also ;-)

Did you transfer it?
Who is / will maintain it?

There are severel adapters which need an maintainance urgently. At community. I tried to mark them at info list hoping that someone reacts. Take a lokk there. I will notebitcat meeting if i can attend. Othereise I will send a zelegram message once a month noting those communuty adapters which gave a serious problem.

**Comment by Apollon77** [comment]
it is in no case a complete transfer because noone updated URLs yet :)

**Comment by mcm1957** [comment]
Ähmm ...
Do not even see the repo within communit orga.
Where do youcsee some transfer?

Besides of this info do not spend to much time for this. I ll check after bathing holiday.

**Comment by Apollon77** [comment]
ahhhhh shit I mixed adapters ...sooory ... yes proceed as ppsted above. remove and inform dev. Sorry for confusion

**Comment by mcm1957** [comment]
Issue at adapters repo created:
https://github.com/Flashy-GER/ioBroker.blink4home/issues/50

Adapetr removed from Repo
https://github.com/ioBroker/ioBroker.repositories/pull/2293
