### ISSUE TITLE
Development and Coding best practices: password encrytion not working properly (after following all steps)

### ISSUE THREAD

**Issue by git-kick** [ioBroker/ioBroker.repositories#2316]
Hi, I am referring to the [Development and Coding best practices](https://github.com/ioBroker/ioBroker.repositories#development-and-coding-best-practices), namely:

> if you need to store passwords please encrypt them. This can be done by just configuration:
> -  Add an array with the relevant config field names in io-package.json in encryptedNative. Additionally, please also protect the access to this field by also providing protectedNative (see e.g. https://github.com/TA2k/ioBroker.psa/blob/master/io-package.json#L81-L82)
> -  Additionally, you need to provide a dependency to js-controller >= 3.0.0 and admin >= 4.0.9 (Admin needs to be a globalDependency, see https://github.com/TA2k/ioBroker.psa/blob/master/io-package.json#L75-L80 and https://github.com/TA2k/ioBroker.psa/blob/master/io-package.json#L70-L74)
> -  That's it. Encryption before storing the fields and decryption before adapter is executed is done automatically.
> -  If you have an older implementation that uses encrypt/decrypt functions in index(_m).html and in main.js you can just convert to this by removing the extra encrypt/decrypt usages in all places and do the above.

I followed all steps thoroughly in a [branch](https://github.com/git-kick/ioBroker.e3dc-rscp/tree/password-encryption) of my adapter.
I also compared relevant files (`io-package.json`, `main.js`, `index_m.html`, and others) and tried to create analogy with the [psa](https://github.com/TA2k/ioBroker.psa) adapter.

**But still, something goes wrong:** 

- when I initialize password = "abc" in `io-package.json`, then the instance configuration page shows  "PQ"
- In main.js, when evaluating `this.config.password`, I always get "f22b6e7c2ec900cb41ad09cedfbb66949ce016f36fa7647f"

Is there some help? What did I miss? Thx.

**Comment by mcm1957** [comment]
First a hint:
Such questions should be asked at telegram channel (or synched discord channel) as you will get an answer ther faster:
https://t.me/+gsX-e8k4mLtmZjZk

I think, that the password cannot be initialized using io-package.json, but that can be answered by more experienced developers at telegram. Initialization must be done (if really usefual as default passwords should be avoided where possible) at gui code - or jsonConfig.

As far as I know, the password CANNOT be displayed at the config page once stored; the config page does not allow a retrieval of the password. Normally (using jsonConfig) password elements only show **** when dsiplaying password fields. Only when entering data (and displying is allowed) the password is shown.

So did you try to enter a new password, store the config and retrieve ist from adapter code? This should work.

Please note that - as far as I know - changing password encryption methos or adding it - requires the users to enter there password one time after upgrade. So perfom ing this change requires an hint at releasenotes and or a news messages to avoid confusion to users.

**Comment by git-kick** [comment]
Thank you for picking up my (obviously misplaced) issue.

Unfortunately, Telegram will not work for me - I wilfully have left it behind because I think it is a platform for many bad things.

 > I think, that the password cannot be initialized using io-package.json, but that can be answered by more experienced developers at telegram. Initialization must be done (if really usefual as default passwords should be avoided where possible) at gui code - or jsonConfig.

I initialized the password only for testing. Best Practices says that `io-package.json` is the right place to initialize native vars.


> Only when entering data (and displying is allowed) the password is shown.

In my case, I can enter the password in the config page, save it, and I can see it after reopening the config page. But I cannot access the value from main.js using `this.config.password`

I think I will stay with my current (working) code and cut the branch, unless I find some docs explaining how the "standard" encryption mentioned in the Best Pracrices works.

Thanks again for your effort!

**Comment by mcm1957** [comment]
I m not sure wether the encryption dors not work with old (non jsonConfig and non React) config or not. Docu reads as it should ....

But its fully ok to leave working vode as it is.

If you want to avoid telegram you could possible use discord. The channels sre synced and you get identical help. If this is an option let me know. Im not using discord but i will orfanize the invite links.

Forum could be another support place. But forum is most used for user support an jacascript adapter. Real afapter dev suport is less common hhrre.

**Comment by git-kick** [comment]
> If this is an option let me know. Im not using discord but i will orfanize the invite links.

Yes, I will try Discord if you could give me the links needed.

**Comment by Apollon77** [comment]
passwords should not be initialized when encrypted. it is that simple :-) In my eyes it makes no sense to initialize passwords at all

**Comment by git-kick** [comment]
As I wrote: I initialized the password only for testing.
I intended to make the problem clear.
Password encryption, as described, does not work at all in my case.

This is why I try to investigate further.
My adapter release did never and will never initialize a password.
