### ISSUE TITLE
[CHECK] Adapter binance needs verification

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.repositories#2322]
# Adapter binance needs verification:

Repository Kartax/binance is archived

Adapter binance is currently installed 492 times

- [x] verify that repository https://github.com/Kartax/binance is really archived
- [x] check if adapter has been migrated but links are not yet updated at repository
      fix links at repository if this is causing the problem
- [x] decide if adapter should (and can) be moved to community-adapters (current usage 492 installs)
- [ ] move adapter to iobroker-community-adapters or 
      remove adapter from repositories

**Comment by mcm1957** [comment]
I had a look at the adapter. Looks like the basic functionality should be testable without trading crypto values.
So I would suggest to try to move it to community area.  (Current usage of nearly 500 users seems to rectify effort)

I can do this if desired. Will discusss with Apollon after his holidays.
If some other maintainer is available - no problem of course :-)

**Comment by Apollon77** [comment]
I would remove it ... the installed ones will still work ...

**Comment by mcm1957** [comment]
OK, I'll do this
