### ISSUE TITLE
[CHECK] Adapter landroid needs verification

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.repositories#2643]
# Adapter landroid needs verification:

Repository iobroker-community-adapters/ioBroker.landroid is archived

Adapter landroid is currently installed 834 times

- [x] verify that repository https://github.com/iobroker-community-adapters/ioBroker.landroid is really archived
- [x] check if adapter has been migrated but links are not yet updated at repository
      fix links at repository if this is causing the problem
- [x] decide if adapter should (and can) be moved to community-adapters (current usage 834 installs)
- [ ] move adapter to iobroker-community-adapters 

or 

- [x] create deprecation news id required
- [x] remove from stable
- [x] remove from latest

**Comment by mcm1957** [comment]
reminder 1.4.2024
remove from latest
