### ISSUE TITLE
Badge active installs, version stable, version latest

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/ioBroker.repositories#276]
It would be Nice if we can have a badge like NPM with amount of "active installation, version stable, version latest" of the adapter like shown on : "http://download.iobroker.net/list.html"

<img width="321" alt="schermafbeelding 2019-01-19 om 02 12 09" src="https://user-images.githubusercontent.com/7318445/51420085-a8561d80-1b8f-11e9-8136-835f0939edc6.png">

**Comment by Apollon77** [comment]
Cool idea.

**Comment by ldittmar81** [comment]
npm version ist drin - also latest.

**Comment by DutchmanNL** [comment]
Genau!

Also welche Version ist stable und welche im latest + Anzahl aktiver Installationen währen cool.

Dan auch integrieren im adapter Template und alle readme habe die badges

**Comment by GermanBluefox** [comment]
Wirklich coole idea

**Comment by GermanBluefox** [comment]
There is no need for version latest because it is npm version.
But "installed" and "stable" are done.

http://iobroker.live/badges/admin-installed.svg
http://iobroker.live/badges/admin-stable.svg

**Comment by DutchmanNL** [comment]
Great thank you!

**Comment by Apollon77** [comment]
A PR for all repos to add those badges will come soon!!

**Comment by Grizzelbee** [comment]
Hmm. Ich habe ein seltsames Phänomen mit den beiden Badges:

Je nachdem von wo aus ich die abrufe, bekomme ich unterschiedliche Werte angezeigt (sehe Bild).

Lokal abgerufen variiert nur die Anzahl der Installationen leicht - komisch, aber meinetwegen.
Von Github aus erkennt das aber deutlich weniger Installationen und die Stable gar nicht.
Eingebunden sind die über folgenden Code:
```
 [...]
 ![Number of Installations](http://iobroker.live/badges/mielecloudservice-installed.svg)
 [![Downloads](https://img.shields.io/npm/dm/iobroker.mielecloudservice.svg)](https://www.npmjs.com/package/iobroker.mielecloudservice)
 ![Number of Installations](http://iobroker.live/badges/mielecloudservice-stable.svg)
 [...]
```
(Wenn ich den Code nicht als solchen markiere und den PreView aufrufe passiert übrigens das Selbe wie bei GitHub)

Kann es sein, dass es noch ein Problem mit den beiden Badges gibt?
Wahrscheinlicher ist zwar, das ich einen Fehler beim Einbinden mache, aber ich sehe ihn einfach nicht.

Kann da bitte mal jemand drüber gucken?


![grafik](https://user-images.githubusercontent.com/5459426/76504394-ee330c80-6447-11ea-92d3-2e5671f2a7e9.png)

**Comment by Apollon77** [comment]
Mal Broewsercache gelöscht? Ich hatte auch schonmal solche effekte, lag irgendwie am broewsercache

**Comment by Grizzelbee** [comment]
Ja. Habe ich. Das ändert nichts. Aus Edge heraus habe ich ebenfalls das Problem. Genauso in einem komplett frisch installierten Chrome.
Für mich sieht das fast wie ein Rechteproblem aus, weil die Anfrage von Github kommt.

**Comment by braindead1** [comment]
Ich habe bei meinem Adapter genau das selbe Problem. Gibt es einen Workaround?

![badge1](https://user-images.githubusercontent.com/2136249/78456993-69828980-76a7-11ea-9cf8-a0b32db6fe34.png)
![badge2](https://user-images.githubusercontent.com/2136249/78456997-6c7d7a00-76a7-11ea-907d-32155bb4cf50.png)

**Comment by afuerhoff** [comment]
Bei mir das gleiche bei stable.
![image](https://user-images.githubusercontent.com/50245893/83355530-49e2a700-a360-11ea-97a4-998a9a528281.png)
![image](https://user-images.githubusercontent.com/50245893/83355541-5a931d00-a360-11ea-8498-2df4dc50bee4.png)
