### ISSUE TITLE
no such file or directory, mkdir '/opt/iobroker/node_modules/iobroker-data/plenticore.0' after js.update

### ISSUE THREAD

**Issue by andre-bu** [ioBroker/ioBroker.repositories#2849]
Hello after updating to js.controller 5.0.12 I get this error message.
I have now updated from Versuon 2.2.0 to version 2.3.0. The problem remains
Thank you for your effort

js.controller 5.0.12
NPM 9.6.7
Node.js 18.17.1

`<html><body>

plenticore.0 | 2023-10-30 17:09:45.518 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
plenticore.0 | 2023-10-30 17:09:44.525 | error | Exception-Code:  ERR_INVALID_ARG_TYPE: The "path" argument must be of type string or an  instance of Buffer or URL. Received undefined
plenticore.0 | 2023-10-30 17:09:44.523 | error | TypeError  [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or  an instance of Buffer or URL. Received undefined     at Object.openSync (node:fs:595:10)     at Object.writeFileSync (node:fs:2324:35)     at Object.unload  (/opt/iobroker/node_modules/iobroker.plenticore/lib/plenticore.js:789:5)     at AdapterClass.<anonymous>  (/opt/iobroker/node_modules/iobroker.plenticore/main.js:40:14)     at AdapterClass.emit (node:events:514:28)     at AdapterClass._stop  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:1369:26)     at AdapterClass._exceptionHandler  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:9113:18)     at process.processTicksAndRejections  (node:internal/process/task_queues:95:5)
plenticore.0 | 2023-10-30 17:09:44.519 | error | unhandled promise rejection: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
plenticore.0 | 2023-10-30 17:09:44.518 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
plenticore.0 | 2023-10-30 17:09:44.501 | error | Exception-Code: ENOENT: ENOENT: no such file or directory, mkdir '/opt/iobroker/node_modules/iobroker-data/plenticore.0'
plenticore.0 | 2023-10-30 17:09:44.500 | error | Error: ENOENT: no such file or directory, mkdir '/opt/iobroker/node_modules/iobroker-data/plenticore.0'     at Object.mkdirSync (node:fs:1398:3)     at Object.setup (/opt/iobroker/node_modules/iobroker.plenticore/lib/plenticore.js:711:6)     at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.plenticore/main.js:189:17)     at process.processImmediate (node:internal/timers:478:21)
plenticore.0 | 2023-10-30 17:09:44.497 | error | uncaught exception: ENOENT: no such file or directory, mkdir '/opt/iobroker/node_modules/iobroker-data/plenticore.0'
plenticore.0 | 2023-10-30 17:09:44.491 | info | [INFO] Configured polling interval: 20000
plenticore.0 | 2023-10-30 17:09:44.489 | info | Configured battery strategy is: 1
plenticore.0 | 2023-10-30 17:09:44.488 | info | Configured maximum feed-in power is 5000
plenticore.0 | 2023-10-30 17:09:44.486 | info | Configured Wp of panel(s) is 0
plenticore.0 | 2023-10-30 17:09:44.426 | info | [START] Starting adapter plenticore v2.3.0r237
plenticore.0 | 2023-10-30 17:09:44.348 | info | starting. Version 2.3.0 in /opt/iobroker/node_modules/iobroker.plenticore, node: v18.17.1, js-controller: 5.0.12
plenticore.0 | 2023-10-30 17:09:09.432 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
plenticore.0 | 2023-10-30 17:09:08.439 | error | Exception-Code:  ERR_INVALID_ARG_TYPE: The "path" argument must be of type string or an  instance of Buffer or URL. Received undefined
plenticore.0 | 2023-10-30 17:09:08.438 | error | TypeError  [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or  an instance of Buffer or URL. Received undefined     at Object.openSync (node:fs:595:10)     at Object.writeFileSync (node:fs:2324:35)     at Object.unload  (/opt/iobroker/node_modules/iobroker.plenticore/lib/plenticore.js:789:5)     at AdapterClass.<anonymous>  (/opt/iobroker/node_modules/iobroker.plenticore/main.js:40:14)     at AdapterClass.emit (node:events:514:28)     at AdapterClass._stop  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:1369:26)     at AdapterClass._exceptionHandler  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:9113:18)     at process.processTicksAndRejections  (node:internal/process/task_queues:95:5)
plenticore.0 | 2023-10-30 17:09:08.432 | error | unhandled promise rejection: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
plenticore.0 | 2023-10-30 17:09:08.431 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
plenticore.0 | 2023-10-30 17:09:08.387 | error | Exception-Code: ENOENT: ENOENT: no such file or directory, mkdir '/opt/iobroker/node_modules/iobroker-data/plenticore.0'
plenticore.0 | 2023-10-30 17:09:08.385 | error | Error: ENOENT: no such file or directory, mkdir '/opt/iobroker/node_modules/iobroker-data/plenticore.0'     at Object.mkdirSync (node:fs:1398:3)     at Object.setup (/opt/iobroker/node_modules/iobroker.plenticore/lib/plenticore.js:711:6)     at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.plenticore/main.js:189:17)     at process.processImmediate (node:internal/timers:478:21)
plenticore.0 | 2023-10-30 17:09:08.380 | error | uncaught exception: ENOENT: no such file or directory, mkdir '/opt/iobroker/node_modules/iobroker-data/plenticore.0'
plenticore.0 | 2023-10-30 17:09:08.373 | info | [INFO] Configured polling interval: 20000
plenticore.0 | 2023-10-30 17:09:08.370 | info | Configured battery strategy is: 1
plenticore.0 | 2023-10-30 17:09:08.369 | info | Configured maximum feed-in power is 5000
plenticore.0 | 2023-10-30 17:09:08.367 | info | Configured Wp of panel(s) is 0
plenticore.0 | 2023-10-30 17:09:08.295 | info | [START] Starting adapter plenticore v2.3.0r237
plenticore.0 | 2023-10-30 17:09:08.229 | info | starting. Version 2.3.0 in /opt/iobroker/node_modules/iobroker.plenticore, node: v18.17.1, js-controller: 5.0.12
plenticore.0 | 2023-10-30 17:08:33.385 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
plenticore.0 | 2023-10-30 17:08:32.392 | error | Exception-Code:  ERR_INVALID_ARG_TYPE: The "path" argument must be of type string or an  instance of Buffer or URL. Received undefined
plenticore.0 | 2023-10-30 17:08:32.391 | error | TypeError  [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or  an instance of Buffer or URL. Received undefined    at Object.openSync  (node:fs:595:10)    at Object.writeFileSync (node:fs:2324:35)    at  Object.unload  (/opt/iobroker/node_modules/iobroker.plenticore/lib/plenticore.js:789:5)     at AdapterClass.<anonymous>  (/opt/iobroker/node_modules/iobroker.plenticore/main.js:40:14)    at  AdapterClass.emit (node:events:514:28)    at AdapterClass._stop  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:1369:26)     at AdapterClass._exceptionHandler  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:9113:18)     at process.processTicksAndRejections  (node:internal/process/task_queues:95:5)
plenticore.0 | 2023-10-30 17:08:32.386 | error | unhandled promise rejection: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
plenticore.0 | 2023-10-30 17:08:32.384 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
plenticore.0 | 2023-10-30 17:08:32.357 | error | Exception-Code: ENOENT: ENOENT: no such file or directory, mkdir '/opt/iobroker/node_modules/iobroker-data/plenticore.0'
plenticore.0 | 2023-10-30 17:08:32.356 | error | Error:  ENOENT: no such file or directory, mkdir  '/opt/iobroker/node_modules/iobroker-data/plenticore.0'    at  Object.mkdirSync (node:fs:1398:3)    at Object.setup  (/opt/iobroker/node_modules/iobroker.plenticore/lib/plenticore.js:711:6)     at Immediate.<anonymous>  (/opt/iobroker/node_modules/iobroker.plenticore/main.js:189:17)    at  process.processImmediate (node:internal/timers:478:21)
plenticore.0 | 2023-10-30 17:08:32.353 | error | uncaught exception: ENOENT: no such file or directory, mkdir '/opt/iobroker/node_modules/iobroker-data/plenticore.0'

</body>
</html>`

**Comment by mcm1957** [comment]
This is a problem with the adapter.
Please check issues at adapter directory or create a new one there.

This repository is definitly not the correct place to open issues for an adapter problem.

(Anyway: seesm to be issue https://github.com/pixcept/ioBroker.plenticore/issues/84 which is still open. Please contact developer of adapter)

**Comment by andre-bu** [comment]
@mcm1957 oh yeah, sorry I was on the wrong page.
