### ISSUE TITLE
Automatic email notification if latest and stable version differs after a period of days

### ISSUE THREAD

**Issue by schmupu** [ioBroker/ioBroker.repositories#285]
Unfortunately, the Adapter developer (me too) forgets often to adjust the version in the stable repository after publishing a new latest version after a while.
Is it possible to send an reminder email to the developer after a period x days (for example 2 weeks) if the latest and stable versions are differently?

**Comment by hash99** [comment]
Hi, 
I must check. Sorry. It's late.

**Comment by foxriver76** [comment]
I think the current check and opening an issue should pretty much satisfy your feature request.
