### ISSUE TITLE
Set stable tags on merge for predefined adapters/controller

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/ioBroker.repositories#2936]
For example `js-controller` relies heavily on the npm `stable` tag for the installer
The same goes for all preinstalled adapters, i.e. `admin`, `backitup` and `discovery`
Personally I often forget to set these tags, and it can be automated in a straightforward way. 

So the idea would be to have a GH action, 

1. running when PR is merged. 
2. Checks if stable has been modified, 
3. extracts adapters and versions from the diff
4. The action defines a static list with these adapters, like `js-controller`, `admin`, .. (can also be extended by anyone who needs it). 
5. if adapter from diff is in static list, execute the following command
6. `npm dist-tag add iobroker.<adapter name>@<version> stable`

**Comment by mcm1957** [comment]
@foxriver76 
@Apollon77 

Can check / implement this for sure.

**Comment by mcm1957** [comment]
Workflow setStableTag has been created and activated.
Test with real data yet missing
