### ISSUE TITLE
sources-dist-stable: js-controller is missin icon entry

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.repositories#2937]
The entry 'icon' is missing at js-controller at sources-dist-stable.json

```
  "jeelink": {
    "meta": "https://raw.githubusercontent.com/foxthefox/ioBroker.jeelink/master/io-package.json",
    "icon": "https://raw.githubusercontent.com/foxthefox/ioBroker.jeelink/master/admin/jeelab_logo.png",
    "type": "hardware",
    "version": "1.2.3"
  },
  "js-controller": {
    "meta": "https://raw.githubusercontent.com/ioBroker/ioBroker.js-controller/master/packages/controller/io-package.json",
    "type": "general",
    "version": "5.0.16"
  },
```

If nothing prohibits this line and there is no expected malfunction, the line should be added to make this entry identical to all other entries. This would reduce risk of problems parsing the data.

@foxriver76 
@Apollon77 

If ok from you side I can add the line.

**Comment by Apollon77** [comment]
ok for me ... I think it is not needed so far because js.cointroller is not shown in the adapterlst, so no logo needed

**Comment by mcm1957** [comment]
added
