### ISSUE TITLE
"vis-2-widgets-gauges" 2x in "sources-dist.json"

### ISSUE THREAD

**Issue by Steiger04** [ioBroker/ioBroker.repositories#3067]
@mcm1957 In der `sources-dist.json` ist `vis-2-widgets-gauges`  2x drin, darum auch eben bei meinem PR diese "komische" Ausgabe.

![image](https://github.com/ioBroker/ioBroker.repositories/assets/17086944/e943ce39-b13d-493e-b785-640c690b0537)

**Comment by mcm1957** [comment]
Ups ....
ÐANKE fürs Finden.
