### ISSUE TITLE
[CHECK] Adapter info needs verification

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.repositories#3277]
# Adapter info needs verification:

Repository iobroker-community-adapters/ioBroker.info is archived

Adapter info is currently installed 30690 times

- [x] verify that repository https://github.com/iobroker-community-adapters/ioBroker.info is really archived
- [x] check if adapter has been migrated but links are not yet updated at repository
      fix links at repository if this is causing the problem
- [x] decide if adapter should (and can) be moved to community-adapters (current usage 30690 installs)
- [ ] move adapter to iobroker-community-adapters 

or 

- [x] create deprecation news id required
- [x] remove from stable
- [x] remove from latest

**Comment by mcm1957** [comment]
reminder 1.4.2024
remove from latest
