### ISSUE TITLE
Authors example links are broken

### ISSUE THREAD

**Issue by LightVolk** [ioBroker/ioBroker.repositories#365]
https://github.com/ioBroker/ioBroker.repositories#authors

All links about authors broken.

Also, some Testing links broken too

**Comment by GermanBluefox** [comment]
TODO: Replace paths with https://github.com/ioBroker/ioBroker.template/blob/master/JavaScript/package.json and https://github.com/ioBroker/ioBroker.template/blob/master/JavaScript/package-io.json

**Comment by GermanBluefox** [comment]
Done

**Comment by LightVolk** [comment]
Thank you!
