### ISSUE TITLE
Consider adding one decimal place to installation badges (1.0k - 9.9k)

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.repositories#377]
This is what I see in the BLE repo: ![grafik](https://user-images.githubusercontent.com/17641229/55218028-2fafb500-5201-11e9-96f1-b7c4121f6a31.png)
It seems that the numbers are rounded, so this can be anything from 500 to 1499. Adding one decimal place (**1.4 k** in this case) would add a lot of information.
Maybe even limit it to numbers below 10k:
* 1.0 k ... 9.9 k - one decimal place
* 10 k ... infinity - no decimal place

**Comment by ldittmar81** [comment]
Why no decimal place after 9.9k? From 10k to 11k is a very long way.... and this can make developers sad. :disappointed:

**Comment by AlCalzone** [comment]
Because of the space in the badge mainly

**Comment by GermanBluefox** [comment]
Done
