### ISSUE TITLE
New App Version 1.22.0

### ISSUE THREAD

**Issue by nacho26** [ioBroker/ioBroker.repositories#4257]
Hello since one week or so a new App Version is out 1.22.0. In Git Hub there is a reference of 1.21.0

With App Version 1.21.0 I got this error message:
Service error: Request failed with status code 401New version app has been published. Code=4106. Stack: ServiceError: Request failed with status code 401New version app has been published at ComfortCloudClient.handleError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:147:31) at ComfortCloudClient.login (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:66:18) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async PanasonicComfortCloud.onReady (/opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/build/main.js:65:9)

after setting the new App Version 1.22.0 in the Adapter I get this error message and not able to control anymore:

Service error: Request failed with status code 412 Precondition Failed. Code=41201. Stack: ServiceError: Request failed with status code 412 Precondition Failed at ComfortCloudClient.handleError (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:147:31) at ComfortCloudClient.login (/opt/iobroker/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:66:18) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async PanasonicComfortCloud.onReady (/opt/iobroker/node_modules/iobroker.panasonic-comfort-cloud/build/main.js:65:9)

**Comment by mcm1957** [comment]
This repository is dedicated to ioBroker repositories LATEST and STABLE. 

Any error report for any adapter is misplaced here.

Please open 
- a topic at out forum (https://forum.iobroker.net) if you are not sure whether a real probelm exists or something might be broken with your installation. You will likely get fast responses there
- a issue at the ADAPTE repository (ioBroker.{adaptername}) if its more likely that there is a issue with an adapter.

When opening a isse for an apdater alway report version information:
- adapter
- js-controller
- admin
- node
- o/s

and attach a log with instance level set to DEBUG

**Comment by mcm1957** [comment]
Anyway - a Issue seems to exist already.
https://github.com/marc2016/ioBroker.panasonic-comfort-cloud/issues/67

Please contact maintainer if you need more info.
