### ISSUE TITLE
[CHECK] Adapter srm needs verification

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.repositories#4333]
# Adapter srm needs verification:

Repository stephan1827/ioBroker.srm is archived

Adapter srm is currently installed 12 times

- [ ] verify that repository https://github.com/stephan1827/ioBroker.srm is really archived
- [ ] check if adapter has been migrated but links are not yet updated at repository
      fix links at repository if this is causing the problem
- [x] decide if adapter should (and can) be moved to community-adapters (current usage 12 installs)
- [ ] move adapter to iobroker-community-adapters

  or 

- [ ] create deprecation news at admin iF required
- [ ] set reminder to remove from stable (typical after 14 day up to one months)
- [ ] remove from stable
- [ ] set reminder to remove from latest (typical after 3 months)
- [ ] remove from latest

**Comment by mcm1957** [comment]
adapter moved to iobroker-community-adapters
