### ISSUE TITLE
Add a check that certain adapter names are forbidden

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.repositories#507]
because they would break ioBroker, e.g. the `iobroker upgrade <adaptername>` commands or admin object view:
* `all`
* `self`
* `system`
* `alias`

**Comment by GermanBluefox** [comment]
https://github.com/ioBroker/ioBroker.repositories/commit/9846e1fa8a10686fb9b64fd8c4bb5f986be0d7c0
