### ISSUE TITLE
URL dependency missing

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.repositories#513]
```npm run addToLatest -- --name youtube --type misc-data```

leads to

```ERROR: URL is not defined``` @ https://github.com/ioBroker/ioBroker.repositories/blob/master/lib/scripts.js#L440

I've added ```const URL = require('url').URL;``` to the requirements and it worked.
Please add this dependency (if this is the correct solution).

**Comment by AlCalzone** [comment]
I wonder why that worked locally without the require. PR created. Thanks for the report!
