### ISSUE TITLE
NPM Downgrades are not correctly noticed by repository list

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/ioBroker.repositories#527]
This is a very rare scenario. However, it should be handled correctly:
Scenario:

1. Published new adapter version 2.3.0 of iobroker.hue to npm  5 days ago
2. Unpublished this version about an hour later (so also 5 days ago)
     http://repo.iobroker.live/sources-dist-latest.json has already shown 2.3.0
3. Today, the latest repo still shows 2.3.0 as latest, while this version has been removed from npm 5 days ago and npm latest tag is 2.2.3

**Comment by GermanBluefox** [comment]
fixed
