### ISSUE TITLE
Also add engine-node version into repo

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.repositories#567]
...  so that Admin/Controller can use it to not install incompatible versions

**Comment by mcm1957** [comment]
@Apollon77 
Is this issue still relevant in an way?

If still needed:
Should this info be added by user or retrived from some source i.e. from io-package.json?
Should the info incorporated into source dist-sources-*.json or added by converter creating the downloaded files?

**Comment by mcm1957** [comment]
Repodata already contains 'common.node'. This data is merged from package.json during repo build:

https://github.com/ioBroker/ioBroker.repobuilder/blob/d77433836ace11ef9fbfabbb9ddf0e1215623ef5/lib/github.js#L43

So I close her. Please open a ne issue if something is still open.
