### ISSUE TITLE
Automate Stable Selection/Reminders

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.repositories#575]
Developers often forget to bring tested versions into the stable.

We should think about automations. An proposal would be:
* When duration of a version in latest without a following version is > x (14 days) AND 
** installations >y% of all installations (5%?) OR installations > z (50/100?) then automatically move into stable once a week
* When only duration of a version in latest without a following version is > x2 create  github issue in adapter repo to remind developer :-)
* When only duration of a version in latest without a following version is > x3 (30/45?) days  BUT installation numbers not reached also move into stable

**Comment by foxriver76** [comment]
can be closed too ;-)
