### ISSUE TITLE
Some Links not working

### ISSUE THREAD

**Issue by oweitman** [ioBroker/ioBroker.repositories#605]
The Links in the Testing part of the README.md Document to iobroker.template are not working.
The Link to the PDF-Document is not working.

https://github.com/ioBroker/ioBroker.repositories/blob/master/README.md#testing

**Comment by oweitman** [comment]
does anyone have the plan to fix this issue at some point?

**Comment by Apollon77** [comment]
Yes sure as soon as we findtime ... or you do a a PR? ;-)

**Comment by oweitman** [comment]
mal auf deutsch:
da ich vor längerem und aktuell wieder auf der Suche nach Informationen zum testen war, bin ich auf diese Seite gestoßen. Leider ist das Thema testen nur sehr dünn dokumentiert. auch in vielen Adaptern findet man so gut wie keine Tests (abgesehen, von den Standardtests, die sowieso immer ausgeführt werden).
Da ich nicht weiß was auf diesen Seiten stand, kann ich leider keinen PR erstellen.

Der Issue war kein Besserwisser Issue, der sagen sollte, ich habe da einen Fehler entdeckt, sondern ein Hinweis, hier fehlt Info, die benötigt wird.

**Comment by Apollon77** [comment]
Ok, ja das Entwickler Doku noch eher Mau ist ist bekannt, das können wir nur gemeinsam aufbauen. Das einfachste ist aktuell sich in den Entwickler Forum bz Discord/Telegram die nötigen Infos zu holen und zu erarbeiten. Und ja danach vllt in DOku giessen :-)
Der Link zum Template (ja kann ich fixen) hilft dir da aber auch nur bedingt weiter.

Testing findest Du in einigen Adaptern "old Style" (sql, mqtt, sonoff, influxdb, history, daikin, smartmeter, ...). Es gibt generell eher sehr wenige Entwickler die hier ausführlich testen. Die meisten machen nur das Minimum. Mit dem neuen testing ist es richtig da gibts noch eher wenige Entwickler.

Ich habe mit dem neuen testing letztens mal rumprobiert (https://github.com/Apollon77/ioBroker.ph803w/blob/main/test/integration.js) ... am Ende sehr ähnlich zum alten was wie geht, nur methoden sind anders.

Ich habe vor in der nächsten Zeit das ganze "Wie entwickle ich einen Adapter", wie teste ich ... genauer aufzuschreiben ... aber das wird sich garantiert etwas ziehen

**Comment by Apollon77** [comment]
fixed, not nice atm, but at least working links ... we work on beztter adapter developmenrt documentation

**Comment by oweitman** [comment]
thanks.
