### ISSUE TITLE
Please add iobroker.lgtv 1.0.2 to official repo

### ISSUE THREAD

**Issue by SMundt** [ioBroker/ioBroker.repositories#9]
Hello bluefox,

can you add iobroker.lgtv 1.0.2 to the official repo?
https://github.com/SMundt/iobroker.lgtv/

**Comment by Apollon77** [comment]
Hey, yes for sure. Please fork the "ioBroker.repositories" project, add yourself and send as Pull-Request :-)

**Comment by SMundt** [comment]
Hello, 
I need help :)
I've forked iobroker.repositories and now?
Do you have a little tutorial? That's the first time I'm doing this :)
Bluefox had done this before :)

**Comment by Apollon77** [comment]
Sure :-)
Start with "sources-dist.json"

There you can see the informations that are needed for each adapter. essentially 5 lines per adapter. These are currently sorted alphabetically. SO find the correct spot and add the  needed 5 lines for your adapter. The "key" is the name of the adapter "lgtv" in your case.
You can use one of the entries you find there and copy it and then change the needed "meta" and "image" links to the correct URLs for your Adapter.

If you also want to have it is the stable repo then do the same for "sources-dist-stable.json". Be aware that the structure is slightly different and a "version" (1.0.2 in your case as latest stable) is needed.

Do this help?

**Comment by ldittmar81** [comment]
The new version is already on. Can we close this issue?
