### ISSUE TITLE
stable not updated

### ISSUE THREAD

**Issue by sbormann** [ioBroker/ioBroker.repositories#965]
Hi,
kann es sein, dass die stable versionen nicht upgedated werden? Z.B. bei iQontrol (betrifft aber auch andere) wurde vor 9d die neue stable gemerged, auf github und in der Adapter-Liste steht aber immer noch die alte Version.
VG!

**Comment by GermanBluefox** [comment]
Kann nicht sein. Aktuell unter http://repo.iobroker.live/sources-dist.json sieht man, dass iQontrol die Version 1.3.3 hat.
Genauso wie in https://github.com/ioBroker/ioBroker.repositories/blob/master/sources-dist-stable.json#L596

**Comment by sbormann** [comment]
Verrückt, heute passt es. Ich bin mir aber echt sicher, gestern stand da noch die 1.2.2 (trotz Reload, Cache löschen etc.)!
Egal, hauptsache es geht. Danke.
![image](https://user-images.githubusercontent.com/49171332/97870325-20fd7e00-1d13-11eb-9637-e28eca538e9a.png)
